### PR TITLE
Change updated and openstack component removed.

### PR DESCRIPTION
**Pull request by skanthed**
Last time PR was from my master branch.
This time, But from now on will be using this branch for PR .

### CODE REVIEW

**Comment by gagansk** [comment]
@skanthed Why do we still have storyboards? @nikunjdoshi67 Is it required?

Also, please remove all the unwanted hidden files like .prettierrc

**Comment by skanthed** [comment]
> @skanthed Why do we still have storyboards? @nikunjdoshi67 Is it required?
> 
> Also, please remove all the unwanted hidden files like .prettierrc

I had discussion with Nikunj. He told we still need storyborads. We can't delete them. I have removed some files. But still kept some which are not necessary because there are removed in Nikunj's PR. It will be updated when everything is merged.

**Comment by gagansk** [comment]
@skanthed Can I review this PR?

**Comment by skanthed** [comment]
> @skanthed Can I review this PR?

Yes. @gagansk

**Review by gagansk — APPROVED** [review]
LGTM

**Pull request merged**
