### PR TITLE
Added the UI Part

### LINKED ISSUE #1: Create a Simple React Application
Create the base React Project

### LINKED ISSUE #2: Create and Update Readme
Create a Readme which highlights

- What the project is about?

- What are the technical dependencies? 

- How to run and contribute to the project?

### PR DESCRIPTION
**Pull request by nikunjdoshi67**

### CODE REVIEW

**Comment by gagansk** [comment]
Please provide a description of the PR. Link the issue that is related to this PR.

**Comment by nikunjdoshi67** [comment]
The PR contains following information:

Components created as per the layout designed 
Props object to display the messages
Components for the OpenstackButton, Openshift Button
Components for the OpenstackCumilativeInfo, OpenshiftCumilativeInfo that would display the overall results.
Right now I have passed the static data for the values. 
I had created the router components but it's throwing errors so commented router section and removed that snippets
Rightnow the pages dont have a in-depth CSS applied as while I was working on that I was getting couple of errors on that.

**Comment by gagansk** [comment]
**Resolve the following compilation warnings:**

./src/Pages/OpenStack/OpenStackInfoCumilative.js
  Line 2:8:  'PropTypes' is defined but never used  no-unused-vars

./src/Pages/OpenShift/OpenShiftInfoButton.js
  Line 2:8:  'PropTypes' is defined but never used  no-unused-vars
  Line 5:3:  Useless constructor                    no-useless-constructor

./src/Pages/OpenStack/OpenStackInfoButton.js
  Line 2:8:  'PropTypes' is defined but never used  no-unused-vars
  Line 5:3:  Useless constructor                    no-useless-constructor

./src/Pages/OpenShift/OpenShiftInfoCumilativeData.js
  Line 5:3:  Useless constructor  no-useless-constructor

./src/Pages/OpenStack/OpenStackInfoCumilativeData.js
  Line 5:3:  Useless constructor  no-useless-constructor

./src/Pages/OpenShift/OpenShiftInfo.js
  Line 7:3:  Useless constructor  no-useless-constructor

./src/Pages/OpenStack/OpenStackInfo.js
  Line 7:3:  Useless constructor  no-useless-constructor

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

**Comment by gagansk** [comment]
@nikunjdoshi67 Please make sure that there are no warnings before making a PR.

**Review by gagansk — APPROVED** [review]
Placeholder Project.

LGTM

**Pull request merged**
